networks:
  loki:
    driver: bridge

services:

  # Serviço que gera os logs
  gerador-logs:
    image: fabricioveronez/gerador-log
    ports:
      - 8080:5000
    volumes:
      - "./logs/gerador-log:/logs"  # Volume onde o gerador de log salva os logs
    networks:
      - loki

  # Serviço Logstash para processar os logs
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash_data:/var/logstash/data
    networks:
      - loki
    depends_on:
      - loki

  # Serviço Loki para armazenamento centralizado de logs
  loki:
    image: grafana/loki:latest
    networks:
      - loki

  # Serviço Promtail para coletar e enviar logs para o Loki
  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    networks:
      - loki
    volumes:
      - ./promtail/config:/etc/promtail/config
      - ./promtail/position:/etc/promtail/position
      - logstash_data:/var/logstash/data
    depends_on:
      - loki

  # Serviço Grafana para visualização de logs
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - loki

  # Serviço Nginx para proxy reverso (opcional, para acesso à Grafana)
  nginx:
    image: nginx:latest
    ports:
      - "3100:80"
    networks:
      - loki
    depends_on:
      - loki
    volumes:
      - ./loki/config/nginx-loki.conf:/etc/nginx/conf.d/default.conf  # Configuração do Nginx para proxy reverso

# Definição do volume logstash_data
volumes:
  logstash_data:
