server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_logs  
    static_configs:
      - targets:
          - nginx-s3-like:80  
        labels:
          job: nginx_logs  
          __path__: /var/log/nginx/*.log  
          
